CREATE TABLE hacker_profiles (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    gender VARCHAR(50) DEFAULT '',
    tshirt_size VARCHAR(20) DEFAULT '',
    city VARCHAR(255) DEFAULT '',
    phone_number VARCHAR(50) DEFAULT '',
    emergency_contact_name VARCHAR(255) DEFAULT '',
    emergency_contact_number VARCHAR(50) DEFAULT '',
    bio TEXT DEFAULT '',
    readme_md TEXT DEFAULT '',
    has_formal_education BOOLEAN DEFAULT false,
    degree_type VARCHAR(255) DEFAULT '',
    institution VARCHAR(255) DEFAULT '',
    field_of_study VARCHAR(255) DEFAULT '',
    grad_year INT DEFAULT 0,
    grad_month VARCHAR(50) DEFAULT '',
    dietary_preference VARCHAR(255) DEFAULT '',
    allergies TEXT DEFAULT '',
    github_url VARCHAR(255) DEFAULT '',
    linkedin_url VARCHAR(255) DEFAULT '',
    resume_url VARCHAR(255) DEFAULT '',
    skills TEXT DEFAULT '',
    default_team_preference VARCHAR(50) DEFAULT 'Solo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
