plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.matrix.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.matrix.app'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    implementation 'com.google.code.gson:gson:2.10.1'

    // Firebase BoM - manages all Firebase library versions
    implementation platform('com.google.firebase:firebase-bom:33.1.0')
    // Firebase Cloud Messaging
    implementation 'com.google.firebase:firebase-messaging'
}

